### ISSUE TITLE
Events that repeat forever

### ISSUE THREAD

**Issue by real-or-random** [johngrogg/ics-parser#12]
Hi, 

this is a follow-up on 2fd2db6e59229bde7bed2b2745677bc995b6611b and 197975ba35f9767ed4cd2333f7ce816a9e4670e0.

The current behavior is inconsistent if I understand the code correctly. Repetitions from an events are returned but only if the event does not repeat forever. In that case, only the first instance of the event is returned.

I think the cleanest solution for the user of the API is that ``eventsFromRange()`` just returns all events in the correct range, with all repetitions. It's just not clear what should happen if the end date of the range is not given. This parameter might even be mandatory: if no recurring events are expected, then one can still set it explicitly far into the future (even the maximal timestamp), or just use ``getEvents()``. 

This could be implemented by generating some of the events (next four years) and generating more only once ``eventsFromRange()`` needs them.

**Comment by u01jmg3** [comment]
There is also this hack for `YEARLY` which is still in place which forces only 2 years worth of events: [class.iCalReader.php#L385-386](https://github.com/johngrogg/ics-parser/blob/7e28444c48fd112a90b292db075a49482c5b5186/class.iCalReader.php#L385-386).

Would be cleaner to be consistent throughout

**Comment by real-or-random** [comment]
Hm I see. Can you provide some background on the behavior of Exchange? Is there a sample file?

**Comment by u01jmg3** [comment]
I'm currently parsing iCal files which have been produced by the export method of Outlook 2013 but I am not the author of this particular hack so I have no sample file of this scenario. I'm currently preparing a PR which will simply define a default `$until` value should neither UNTIL nor COUNT be defined which should cover most circumstances.

**Comment by u01jmg3** [comment]
@real-or-random does this commit (5aae755) help?

**Comment by real-or-random** [comment]
Thanks, it's not hackish anymore now. I think it is not optimal yet but fine for my needs. I will create a pull request if I need more. :)

**Comment by u01jmg3** [comment]
Yes agreed - not optimal so PR welcome :)

Especially regarding #19 whereby you might not want to include in the past events of an indefinite recurring booking
