### ISSUE TITLE
Link to original project

### ISSUE THREAD

**Issue by MartinThoma** [johngrogg/ics-parser#18]
Hello,

could you please update the link from google code to https://github.com/MartinThoma/ics-parser?

Best regards,
Martin

**Comment by real-or-random** [comment]
There are more links in class.iCalReader.php and in the GitHub project description (below the title).

**Comment by u01jmg3** [comment]
I'm currently preparing a PR where I'll swap the links in class.iCalReader.php

@johngrogg can you edit the repo description? Collaborator role doesn't allow me to

**Comment by johngrogg** [comment]
Done. Does anyone happen to know if I can retroactively set this repo up as a fork of @MartinThoma's repo? It would be nice if the fixes I made in the past and the fixes @u01jmg3 and others have been making recently could be more easily available to @MartinThoma.

**Comment by u01jmg3** [comment]
Sorry I know no way of doing a retrospective fork although would be useful to do under the circumstances

**Comment by MartinThoma** [comment]
@johngrogg Thank you very much!

**Comment by real-or-random** [comment]
The only way is to delete this repo on GitHub, fork the original one, and then push to the fork. 

The only drawback: All the issues and pull requests are gone. However, this would create not too much overhead in this early stage. There are only six open issues at the moment. So it would be a good idea to do it now.

Depending on @MartinThoma 's plans, it could also be easier not to fork at all, and just use his repo. 
Managing a fork creates usually just unnecessary overhead. 
If he is not interested at all in maintaining it (which I don't assume), he could even transfer his repo.

**Comment by MartinThoma** [comment]
@real-or-random I don't think I will continue ics-parser. I just wanted the existing links to work. I think I'll add a link to this repository and a note that the work on mine will not be continued.

**Comment by u01jmg3** [comment]
Looks like all is good then :)
