### ISSUE TITLE
Only show today's events

### ISSUE THREAD

**Issue by djollie029** [johngrogg/ics-parser#19]
How do I get the ics-parser to only display today's events?
Currently it lists all past events right back to the beginning of the year.
I just need the current days to display.

Thank you

**Comment by u01jmg3** [comment]
Do you have an example iCal file? Just paste the contents here

**Comment by djollie029** [comment]
Hi, It is a big file and contains a lot of info, I have copied some below...

Its from an Office 365 online calendar...

BEGIN:VCALENDAR
METHOD:PUBLISH
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
X-WR-CALNAME:Calendar
BEGIN:VTIMEZONE
TZID:GMT Standard Time
BEGIN:STANDARD
DTSTART:16010101T020000
TZOFFSETFROM:+0100
TZOFFSETTO:+0000
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T010000
TZOFFSETFROM:+0000
TZOFFSETTO:+0100
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
DESCRIPTION:\n\n
UID:040000008200E00074C5B7101A82E00800000000308754F01F95CF01000000000000000
 0100000002A37825565A04D4CB5C2C8043C93CE77
SUMMARY:Year 11 Week
DTSTART;VALUE=DATE:20150112
DTEND;VALUE=DATE:20150117
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20150416T120549Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:FREE
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:TRUE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
BEGIN:VEVENT
UID:040000008200E00074C5B7101A82E00800000000BAB0E16019A0CF01000000000000000
 010000000886D65E4AFEBB740B36CAF70635DC463
SUMMARY:Reflection Theme - RS
DTSTART;VALUE=DATE:20150112
DTEND;VALUE=DATE:20150117
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20150416T120549Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:FREE
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:TRUE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
BEGIN:VEVENT
DESCRIPTION:\n\n
UID:040000008200E00074C5B7101A82E00800000000D0D7D63249EDCF01000000000000000
 0100000005393302090DE344495915867D2A53F29
SUMMARY:Year 11 Pre Public Exams
DTSTART;VALUE=DATE:20150112
DTEND;VALUE=DATE:20150124
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20150416T120549Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:


... and so on...

**Comment by u01jmg3** [comment]
This is functionality that will need to be implemented as it does not exist. PRs welcome but be careful there are implications regarding recurring events.

**Comment by u01jmg3** [comment]
Closing as lack of activity and no PR
