### ISSUE TITLE
Notice message

### ISSUE THREAD

**Issue by blodan** [johngrogg/ics-parser#21]
Hi,

There is a notice when we read our Zimbra ics file because the code expects EXDATE_array to be an array but it hasnt yet been set/initialized it seems.

This patch removes the notice but it might not be the proper solution.
http://filer.p203.se/class.iCalReader.php.patch

**Comment by u01jmg3** [comment]
Are you using the [latest version](https://raw.githubusercontent.com/johngrogg/ics-parser/4d4fbd147e4dac78f8b34b66d3380edefb9f2c4b/class.iCalReader.php)?

This was fixed using:

```php
...
if ((!isset($anEvent['EXDATE_array'])) || (!in_array($anEvent['DTSTART'], $anEvent['EXDATE_array']))) {
    $events[] = $anEvent;
}
...
```

**Comment by blodan** [comment]
Sorry, I used the last stable (1.0.1) on packagist, never tried the dev-master, stupid me.

**Comment by johngrogg** [comment]
I've prepped a new release to help with this. I'll try to prepare a new release after every few pull-requests to make everyone's life easier when trying to use this library.
