### ISSUE TITLE
Support multiline values

### ISSUE THREAD

**Issue by aaronpk** [johngrogg/ics-parser#25]
The ics file I am parsing includes some values that span lines. When the value wraps a line, the next line begins with a space. I was able to pre-process the file to support this by removing the string "newline-space" (`\n `). This should be handled by the parser, though.

**Comment by u01jmg3** [comment]
Thanks for logging this - do you have an example ICS to hand or is it simple enough to replicate the issue by adding in the newline character to fields like summary?

**Comment by aaronpk** [comment]
Here's an example:

```
BEGIN:VCALENDAR
PRODID;X-RICAL-TZSOURCE=TZINFO:-//Airbnb Inc//Hosting Calendar 0.8.8//EN
CALSCALE:GREGORIAN
VERSION:2.0
BEGIN:VEVENT
DTEND;VALUE=DATE:20140531
DTSTART;VALUE=DATE:20140524
UID:xxx@airbnb.com
DESCRIPTION:CHECKIN:  03/18/2014\nCHECKOUT: 03/19/2014\nNIGHTS:   1\nPHO
 NE:    +1 xxx xxx xxxx\nEMAIL:    (no email alias available)\nPROPERTY: 
 Example Property\n
SUMMARY:Guest Name (Confirmation Code)
LOCATION:Example Property
END:VEVENT
```

**Comment by u01jmg3** [comment]
Closed with 4922899

**Comment by u01jmg3** [comment]
Please let me know of any issues

**Comment by schester44** [comment]
Hello, I'm experiencing something similar to this. Still tracking a fix but figured i'd post this here to maybe gain some insight.

I have an .ics file with entries that span multiple lines such as these two:

`X-TRUMBA-CUSTOMFIELD;NAME="Event Type";ID=21;TYPE=number:Library Event T
 ype
X-TRUMBA-CUSTOMFIELD;NAME="Library Branch";ID=16510;TYPE=CustomAsset:Nov
 ato Library`

That ends up being outputted like this:

```
 [xTrumbaCustomfield_array] => Array
                (
                    [0] => Array
                        (
                            [NAME] => Event Type
                            [ID] => 21
                            [TYPE] => number
                        )

                    **[1] => Library Event T
                    [2] =>  ype**
                    [3] => Array
                        (
                            [NAME] => Library Branch
                            [ID] => 16510
                            [TYPE] => CustomAsset
                        )

                    **[4] => Nov
                    [5] =>  ato Library**
                    [6] => Array
                        (
                            [NAME] => Library Image
                            [ID] => 17459
```

"Library Event Type" should be on 1 line but it gets broken into two which creates two array values instead of the expected 1 result. Same goes for the Novato Library, it reads **[4] Nov [5] ato Library** but it should be **[4] Novato Library**

**Comment by u01jmg3** [comment]
- Have you looked at simply the key `X-TRUMBA-CUSTOMFIELD` (not `{field}_array`)?
  - The `{field}_array` consists of  exactly what it sees line per line.
- Provided with this repo is an example using the `DESCRIPTION` field and multi line content

**Comment by schester44** [comment]
Hello, Thanks for the quick response. I did indeed look at the `X-TRUMBA-CUSTOMFIELD` key however, for this data source, every custom field is prefixed with that key which results in one big value of multiple custom fields all concatenated into one string. It appears the `;NAME=""` section of the string is the real unique identifier of these custom fields. I will do some more digging. thanks again!

`X-TRUMBA-CUSTOMFIELD;NAME="Event Type";ID=21;TYPE=number:Library Event Type`

**Comment by u01jmg3** [comment]
If you find a bug along the way, let me know and I will fix it.
