### ISSUE TITLE
Problems parsing BYMONTH 

### ISSUE THREAD

**Issue by myzinsky** [johngrogg/ics-parser#27]
Notice: Undefined index: BYMONTH in /var/www/calendar/ics-parser/class.iCalReader.php on line 490

**Comment by u01jmg3** [comment]
Do you have an example iCal snippet for me to test against? Are you using the latest [dev-master](https://github.com/johngrogg/ics-parser/archive/master.zip) branch?

**Comment by u01jmg3** [comment]
Closing as duplicate of #28
