### ISSUE TITLE
Undefined variable: start_time

### ISSUE THREAD

**Issue by bacinsky** [johngrogg/ics-parser#29]
https://github.com/johngrogg/ics-parser/blob/master/class.iCalReader.php#L503

**Comment by u01jmg3** [comment]
Thanks for logging this issue

Any chance you could provide the iCal snippet which is causing the parser to show this error? It is a bit odd as the `start_time` variable is defined [a few lines up](https://github.com/johngrogg/ics-parser/blob/master/class.iCalReader.php#L496)

**Comment by bacinsky** [comment]
Hi, that's strange. I'm parsing the following http://calendar.zoznam.sk/icalendar/create-vcard-multiple-nameday2.php?fName=sk

**Comment by u01jmg3** [comment]
Using the [latest version](https://github.com/johngrogg/ics-parser/archive/master.zip) I had no problems parsing your iCal file
