### ISSUE TITLE
Ability To Export Calendar Into ICS File?

### ISSUE THREAD

**Issue by Gerst20051** [johngrogg/ics-parser#31]
Can we add the ability to export calendars into ICS?

**Comment by u01jmg3** [comment]
Can you give me a scenario where this would be a requirement?

This repo provides a parser for ICS files so in order to use it you need an ICS file in the first place. Anything more than parsing and this library isn't for that purpose.

**Comment by Gerst20051** [comment]
My Use Case Would Be Combining Multiple ICS Files Into One ICS File.

**Comment by u01jmg3** [comment]
That is achievable although goes beyond what the parser is currently aimed at being used for. There could also be issues when combining ICS files for instance with differing timezone settings, etc.

Feel free to submit a PR if you want to have a go at doing it yourself and I'll review

**Comment by Gerst20051** [comment]
Thanks For The Input. I'll let you know when I'm done.
