### ISSUE TITLE
exdate in repetitive tasks

### ISSUE THREAD

**Issue by tazzon** [johngrogg/ics-parser#32]
I found problems in repetitive tasks. I want to parse an ical from Google Calendar and if event is throughout a day (no hour specified), DTSTART,DTEND and EXDATE are formated YYYYMMDD.
I add this code in process_recurrences function and it seems good.
before:
```php
if ((!isset($anEvent['EXDATE_array'])) || (!in_array($anEvent['DTSTART'], $anEvent['EXDATE_array']))) {}
```
after:
```php
if ((!isset($anEvent['EXDATE_array'])) || (!in_array($anEvent['DTSTART'], $anEvent['EXDATE_array'])) && (!in_array(substr($anEvent['DTSTART'],0,8), $anEvent['EXDATE_array']))) {}
```
There is probably a cleaner solution but this one works fine.

Thank you for this lib.

**Comment by u01jmg3** [comment]
Hi tazzon,

Can you provide a snippet of your iCal file that's causing you this problem so I can reproduce the errors you're seeing? Without this I cannot determine the best course of action.

**Comment by tazzon** [comment]
Hi,

here is a snippet of my ics file.
```
BEGIN:VEVENT
DTSTART;VALUE=DATE:20150909
DTEND;VALUE=DATE:20150910
RRULE:FREQ=DAILY;COUNT=5
EXDATE;VALUE=DATE:20150911
DTSTAMP:20150831T072047Z
UID:0hag8u4m6bjhhn4fp8r8dtc4f8@google.com
CREATED:20150830T073554Z
DESCRIPTION:
LAST-MODIFIED:20150830T073554Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:bbbbbbb
TRANSP:TRANSPARENT
END:VEVENT
```
There is 5 events with daily recurring.
When the function process_recurrences creates recurring events, DTSTAST for each are : 
```
[0]
   DTSTART=20150909
   EXDATE=20150911
[1]
   DTSTART=20150910T000000
   EXDATE=20150911
[2]
   DTSTART=20150911T000000
   EXDATE=20150911
[3]
   DTSTART=20150912T000000
   EXDATE=20150911
[4]
   DTSTART=20150913T000000
   EXDATE=20150911
```
event[0] DTSTART format don't change.
For event [2], it can't find EXDATE_array[20150911T000000], so this event is returned.

I hope this can help you.

**Comment by u01jmg3** [comment]
@tazzon: see if 868e286 solves things

**Comment by tazzon** [comment]
Hi,
This code works fine, I tested and all my recursive events are good.
Thank you for your work.
