### ISSUE TITLE
Help with passing in array of line

### ISSUE THREAD

**Issue by clayton256** [johngrogg/ics-parser#33]
Hi,
I just started using ics-parse for my website. I want to use the feature of passing in an array of lines, instead of a file, because I'm pulling the VCALENDAR data out of a sqlite3 database. Each line is a VCALENDAR "blob". When I pass in the array of lines, the `event_count` is 0 and `$ical->events()` returns NULL. Obviously, my array of lines is incorrect. What should the format of the array of lines be?
Below is a snippet of my code:
```php
$sqldb = new PDO("sqlite:db/db.sqlite") or die(print_r($sqldb->errorInfo(), true));
$sqldb->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
$statement = $sqldb->prepare("select * from calendarobjects where calendarid = 12");
$statement->execute();
$results = $statement->fetchAll(PDO::FETCH_ASSOC);
if ($results)
{
    foreach($results as $i => $row)
    {
        $icsArray[$i] = $row["calendardata"];
    }
}
$ical = new ICal($icsArray);
echo $ical->event_count;
$ics_dates = $ical->events();
echo $ics_dates;
```
Any help is greatly appreciated!
Thanks! Mark

**Comment by u01jmg3** [comment]
Hi Mark,

A few things are incorrect with your code.

Firstly, you can't simply pass an array when instantiating a new ICal object as it is expecting a [filename](https://github.com/johngrogg/ics-parser/blob/master/class.iCalReader.php#L50) which the parser wants to read in line by line. You would also have to iterate over `$icsArray` for each of your calendars returned from your database as each would need to be parsed separately. Finally, [`events()`](https://github.com/johngrogg/ics-parser/blob/master/class.iCalReader.php#L572) (`$ics_dates`) returns an array so you can't just echo it out.

```php
foreach($icsArray as $calendar){
    $calendar = explode("\n", $calendar);
    $ical = new ICal($calendar);
    echo $ical->event_count . "<br />\n";
    $ics_dates = $ical->events();
    var_dump($ics_dates);
}
```

**Comment by clayton256** [comment]
Hi, 

Thanks for the feed back. You're absolutely right about not being able to echo out an array - duh! As for the rest of the code, let me play around with it to see if I can understand what you're recommending.

Thanks again for your help, 
Mark
