### ISSUE TITLE
Need PHP 5.3

### ISSUE THREAD

**Issue by FredericHardy** [johngrogg/ics-parser#39]
Hi,

```
$is_excluded = array_filter($anEvent['EXDATE_array'], function($val) use ($search_date) { return is_string($val) && strpos($search_date, $val) === 0; });
```
is not working in PHP 5.2, you need PHP 5.3: 

syntax error, unexpected T_FUNCTION in class.iCal Reader.php on line 415

Or you have to define the anonymous function outside the array_filter. I would to it but I don't know how to transmit the parameters to the function ($search_date...)

**Comment by u01jmg3** [comment]
To be honest PHP 5.2 was end of life 4 years, 11 months ago so I think you should really be upgrading

**Comment by FredericHardy** [comment]
Yes of course, that was only to let people known that they have to upgrade
before using it.
Thanks for your work.


Frédéric HARDY

2016-01-04 22:01 GMT+01:00 Jonathan Goode <notifications@github.com>:
