### ISSUE TITLE
Recurring Events: last event gets cut off and is not part of the $events array

### ISSUE THREAD

**Issue by Bratzmeister** [johngrogg/ics-parser#42]
Hey there,

I recently (this week) discovered that this happens with events from last year. Especially in calendar2.ics you can reproduce this when using the example.php from this repository with it. When you compare the output with the actual .ics file (i.e. look at the last lines or import it in a calendar application) you will notice in the week from 18th of January 2016 and 24th of January 2016 basically all recurring events end and they are not included in $events.

I am currently taking a look at the 260+ lines function process_recurrences() and found a hint:
The switch case "WEEKLY" in switch ($frequency) starting at line 425 is not localized and ignores the timezone by always using the american scheme for weekdays (week starts on sundays instead of mondays). I can't confirm this yet, but I will look into this tomorrow.

[calendar2.ics.zip](https://github.com/johngrogg/ics-parser/files/97794/calendar2.ics.zip)

[calendar.ics.zip](https://github.com/johngrogg/ics-parser/files/97786/calendar.ics.zip)

**Comment by u01jmg3** [comment]
Thank you for logging this issue but I am going to need you to be more precise with the event that isn't working for you. `calendar.ics` has ~19 recurring events and `calendar2.ics` has ~65 which is too much for me to sift through.

Can you provide an example iCal event -- along with its recurring rule (`RRULE`) -- which you believe is being processed incorrectly and I can begin investigating?

For example:

```ics
BEGIN:VEVENT
DTSTART;VALUE=DATE:20160119
DTEND;VALUE=DATE:20160120
DTSTAMP;TZID="GMT Standard Time":20110121T195741Z
UID:rq8jng4jgq0m1lvpj8486fttu0@google.com
CREATED:20110119T141904Z
DESCRIPTION;LANGUAGE=en-gb:
LAST-MODIFIED:20150409T150000Z
LOCATION:
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY;LANGUAGE=en-gb:test 2
TRANSP:TRANSPARENT
END:VEVENT
```

---

For your information, `WKST` (week start) is not respected so this library will not alter recurring events and understand this rule.

**Comment by Bratzmeister** [comment]
Hello, sorry I was kind of in a hurry.

This one is the missing event from the series I wrote about above in calendar.ics:

BEGIN:VEVENT
RRULE:FREQ=WEEKLY;UNTIL=20160121T103000Z;INTERVAL=1;BYDAY=TH;WKST=MO
EXDATE;TZID=W. Europe Standard Time:20151224T113000,20151231T113000
SUMMARY:WIR: STMD: GB_SAP
DTSTART;TZID=W. Europe Standard Time:20151008T113000
DTEND;TZID=W. Europe Standard Time:20151008T130000
UID:040000008200E00074C5B7101A82E0080000000020A1D4D5C0F6D001000000000000000
 010000000FB56DD5A1CDB7A4D82458FE23D0EE342
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20160120T163623Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:1
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT

**Comment by Bratzmeister** [comment]
I take back the guess with the DST there seems to be a general problem with recurring events. When I use the same calendar.ics file I uploaded and create a new recurring event (I tried daily a daily series with 3 elements) in a small timegap it keeps cutting the last one. Outlook and Evolution both show all 3 elements in the series as it is supposed to be.

**Comment by Bratzmeister** [comment]
I found the cause of the problem.
It lies within the fact that in the .ics `DTSTART` and `DTEND` both lie within the timezone the event was created in, while `RRULE`'s `UNTIL` is always UTC. I made a quick and dirty fix for me which works. If you want I can figure out an universal one to commit here.

**Comment by u01jmg3** [comment]
PR is always welcome
