### ISSUE TITLE
No example on how to get recurrence values

### ISSUE THREAD

**Issue by rashnk** [johngrogg/ics-parser#48]
I have not found in `example.php` how to extract recurrence values from ics

`RRULE:FREQ=WEEKLY;COUNT=5;INTERVAL=2;BYDAY=TU`

`$event['RRULE']` returns as above

**Comment by u01jmg3** [comment]
Recurrence rules are taken care of in the library but if you want to perform some custom logic then you can just extract the code used by [`process_recurrences()`](https://github.com/johngrogg/ics-parser/blob/master/class.iCalReader.php#L328-L336);

```php
require 'class.iCalReader.php';

$ical   = new ICal('MyCal.ics');
$events = $ical->events();

foreach ($events as $event) {
    if (isset($event['RRULE'])) {
        $rrules = array();
        $rrule_strings = explode(';', $event['RRULE']);
        foreach ($rrule_strings as $s) {
            list($k, $v) = explode('=', $s);
            $rrules[$k] = $v;
        }

        print_r($rrules);
    }
}
```

**Comment by samuelstein** [comment]
What does this mean? Will recurring events handled like normals events end therefore parsed as separate events?

**Comment by u01jmg3** [comment]
Correct. `RRULE` will be parsed and converted to single, separate events depending on the makeup of the rule.

e.g. `RRULE:FREQ=DAILY;COUNT=2` with a `DTSTART` of `20190218T150000Z`

Would create two events on Monday and Tuesday.
