### ISSUE TITLE
DURATION not supported

### ISSUE THREAD

**Issue by Nilpferdschaf** [johngrogg/ics-parser#52]
http://www.kanzaki.com/docs/ical/duration.html

The Duration Property is currently not parsed and ics-parser throws an error when there is no DTEND Property.

Something like this would not work:

```
BEGIN:VEVENT
SUMMARY:Test
DTSTART:20160425T150000Z
DURATION:PT1H
UID:calendar-62-e7c39bf02382917349672271dd781c89
END:VEVENT
```

**Comment by u01jmg3** [comment]
Feel free to PR; this library is not currently in active development. Bugs will be fixed but enhancements will be added to a prioritised queue.

**Comment by u01jmg3** [comment]
Does fe46d0d provide what you need?

**Comment by u01jmg3** [comment]
Closing but happy to re-open if problem persists
