### ISSUE TITLE
To ICS support

### ISSUE THREAD

**Issue by gempain** [johngrogg/ics-parser#56]
Hello,

Thanks for the great script, it works like a charm.

IMHO the only missing feature is the ability to print the ICS back to it's original format. Sometimes you just want to parse the ICS, make some modifications and then write it back to an ICS.

All the best,
G.

**Comment by u01jmg3** [comment]
Feel free to PR; this library is not currently in active development. Bugs will be fixed but enhancements will be added to a prioritised queue.

**Comment by gempain** [comment]
Sounds good, I will give it a shot when I get some free time.
