### ISSUE TITLE
eventsFromRange

### ISSUE THREAD

**Issue by jamiegamauf** [johngrogg/ics-parser#6]
Can you submit an example of eventsFromRange?  I cannot get this to work.

**Comment by johngrogg** [comment]
The `$rangeStart` and `$rangeEnd` parameters get fed directly into the constructor of a standard PHP `DateTime` object. This means they should be strings in the format accepted by `strtotime()`.

The method will then return all events that are on or between those dates. If there are not events between those dates it will return false.

Note you have to have initialized an instance of the `ICal` class with a valid .ics file or an array of valid lines from an ical file.

So, as an example:

```php
require 'class.iCalReader.php';
$ical   = new ICal('MyCal.ics');

$marchEvents = $ical->eventsFromRange('2015-03-01', '2015-03-31');

/** 
 * $marchEvents now has any events that were scheduled during march.
 * If there were no events it is now false
 **/
```
