### ISSUE TITLE
installed with composer class.iCalReader.php file differs from the one in source

### ISSUE THREAD

**Issue by burlakko** [johngrogg/ics-parser#64]
I'm not sure if it's a bug or i'm doing something wrong.
After installing ics-parser using composer i found out that installed version of class.iCalReader.php file is different from the one on github source.
Both are marked as 1.0.3 version but the one installed with composer doesn't contain the `initString()` method.

Here is a composer.json code
```json
"require": {
    "johngrogg/ics-parser": "*"
},
```

**Comment by u01jmg3** [comment]
If you want the latest code use `"johngrogg/ics-parser": "dev-master"`. This will pull in the latest commit from master rather than just the current release. I only create new releases once I know the code is stable.
