### ISSUE TITLE
sortEventsWithOrder trying to use ICal\EventObject as array

### ISSUE THREAD

**Issue by leepownall** [johngrogg/ics-parser#80]
I'm trying to use `eventsFromRange()`. This calls `sortEventsWithOrder()`. Inside that method it loops through the array of events (line 1100), each array contains a `ICal\EventObject`. But the code uses array functions and tries to access properties as though it is an array. 

For me, `array_key_exists` fails so then it tries to access as an array and I get:

```php
[Symfony\Component\Debug\Exception\FatalErrorException]  
Cannot use object of type ICal\EventObject as array
```

**Comment by u01jmg3** [comment]
PRs are welcome. Can you provide an iCal snippet?

**Comment by s0600204** [comment]
I believe this may have been fixed by changes to `sortEventsWithOrder()` in #78. @leepownall, could you try using the version of `ICal.php` found within `src/ICal` in this repo and check?

**Comment by falsovsky** [comment]
I just tested this library and had the same problem.

**Comment by leepownall** [comment]
Looks like it has fixed the issue I was getting, although it seems to have highlighted another issue I think. I will investigate further but the it doesn't look like you can use `eventsFromRange()` to get a single day.

The rangeStart and rangeEnd (line 1134, 1135) end up getting set as the beginning of the day, but the actual event is later in the day. So when you do the check for inbetween the two dates it never works.

```
"08.09.2016 00:00:00" = Range Start
"08.09.2016 00:00:00" = Range End
"08.09.2016 09:00:00" = Event Date
```

**Comment by u01jmg3** [comment]
Closing this issue as PR #82 fixes the above - thanks to @s0600204 for their work
